# Nuit example config
# This config is used for, well, configuring the bot. You should use it when self-hosting the bot.
# PLEASE DO NOT DELETE THIS FILE
# It is crucial because it also contains the default config, which some other modules depend on.
# Note: bot tokens and other stuff are stored in .env, not this file or any other file.
# It has different sections that are each explained in this file.
# You should keep this file available as an example until there is a documentation available.
# Check config.toml for the global config used by the Nuit team.
# You can also make a config.private.toml and add it to .gitignore for personal config only.
# config.private.toml has priority over config.toml, so if one contradicts the other, config.private.toml wins.

# This section is for configuring different managing parts of the hosting service.
[host]
# Hosters are people you genuinely trust with the bot.
# They will, at the time of writing this (2026-04-12), be able to reload commands (unless disabled, see host.allow_command_reloading), making most bot commands unusable for a few seconds
# Add them as a string containing their ID in an array like below.
# Even when asked, do NOT add strangers to this list.
hosters = ["1234", "5678"]
# This is related to command reloading.
# A command that's always exposed (unless you delete its files) allows to reload commands (resends the available commands to Discord).
# Only people marked as hoster in host.hosters can run this command regardless of the setting, else they will be met with an error.
# Disabling this will completely disallow the command, outputting an error even to hosters.
# We recommend having this enabled only if this is a development bot and server(s).
allow_command_reloading = false
# Allows installing external modules from registries listed below.
# This will install them all at startup.
# Make sure you trust the registries.
allow_external_modules = true

# Registries are the module catalogs.
# By default, the Nuit registry is recommended because it's reviewed by the Nuit team.
[[registries]]
raw = "https://raw.githubusercontent.com/Nuit-Bot/Registry/refs/heads/main/registry.json"