# Nuit example config
# This config is used for, well, configuring the bot. You should use it when self-hosting the bot.
# PLEASE DO NOT DELETE THIS FILE
# It is crucial because it also contains the default config, which some other modules depend on.
# Note: bot tokens and other stuff are stored in .env, not this file or any other file.
# It has different sections that are each explained in this file.
# You should keep this file available as an example until there is a documentation available.
# Check config.toml for the global config used by the Nuit team.
# You can also make a config.private.toml and add it to .gitignore for personal config only.
# config.private.toml has priority over config.toml, so if one contradicts the other, config.private.toml wins.

# This section is for configuring different managing parts of the hosting service.
[host]
# Allows running external modules from registries listed below.
# Make sure you trust the registries.
allow_external_modules = true

# Registries are the module catalogs.
# By default, the Nuit registry is recommended because it's reviewed by the Nuit team.
[[registries]]
raw = "https://raw.githubusercontent.com/Nuit-Bot/Registry/refs/heads/main/registry.json"
