// Auto-generated by scripts/generate-page-manifest.ts - do not edit.

import type { ComponentType } from "react";

export const modulePages: Record<string, () => Promise<{ default: ComponentType<any> }>> = {

};
