import { mkdir, readdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join, relative, resolve } from "node:path";

type ModulePackage = {
    name?: string;
    nuit?: {
        page?: string;
    };
};

const root = resolve(import.meta.dir, "..");
const manifestPath = join(root, "src", "web", "pages", "modules", "manifest.ts");
const manifestDir = dirname(manifestPath);

function toImportPath(path: string) {
    const normalized = path.replaceAll("\\", "/");
    return normalized.startsWith(".") ? normalized : `./${normalized}`;
}

async function readModulePackages(baseDir: string) {
    const entries = await readdir(baseDir, { withFileTypes: true }).catch(() => []);
    const packages: { name: string; pagePath: string }[] = [];

    for (const entry of entries) {
        if (!entry.isDirectory()) continue;

        const moduleDir = join(baseDir, entry.name);
        const rawPackage = await readFile(join(moduleDir, "package.json"), "utf-8").catch(() => null);
        if (!rawPackage) continue;

        let parsed: ModulePackage;
        try {
            parsed = JSON.parse(rawPackage) as ModulePackage;
        } catch {
            continue;
        }

        if (!parsed.name || !parsed.nuit?.page) continue;

        packages.push({
            name: parsed.name,
            pagePath: resolve(moduleDir, parsed.nuit.page),
        });
    }

    return packages;
}

const modulePackages = [
    ...(await readModulePackages(join(root, "src", "modules"))),
    ...(await readModulePackages(join(root, "registry-modules"))),
];

const entries = modulePackages
    .sort((a, b) => a.name.localeCompare(b.name))
    .map(({ name, pagePath }) => {
        const importPath = toImportPath(relative(manifestDir, pagePath));
        return `    ${JSON.stringify(name)}: () => import(${JSON.stringify(importPath)}),`;
    });

const contents = `// Auto-generated by scripts/generate-page-manifest.ts - do not edit.

import type { ComponentType } from "react";

export const modulePages: Record<string, () => Promise<{ default: ComponentType<any> }>> = {
${entries.join("\n")}
};
`;

await mkdir(manifestDir, { recursive: true });
await writeFile(manifestPath, contents);
